---
name: Create Preview Branch
run-name: Preview by @${{ github.actor }}

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: create-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: write    # Required to checkout, create branches, and push
  actions: read      # Required to run the workflow
  pull-requests: write  # Required to comment on PRs

jobs:
  create-preview:
    runs-on: ubuntu-latest
    env:
      SOURCE_BRANCH: ${{ github.head_ref }}
      GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
    steps:
      # ... existing steps remain the same until the end ...

      - name: Save preview branch info
        run: |
          set -euo pipefail
          
          PREVIEW_BRANCH="${{ steps.branch-name.outputs.branch_name }}"
          SAFE_BRANCH_LOG="${{ steps.validate.outputs.safe_branch_log }}"
          
          echo "[SUCCESS] Preview branch created successfully!"
          echo "[INFO] Branch name: $PREVIEW_BRANCH"
          echo "[INFO] Source branch: $SAFE_BRANCH_LOG"
          echo "[INFO] Source commit: $GITHUB_SHA"
          echo "[INFO] Created at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          echo ""
          echo "[INFO] The preview branch is now ready for Mintlify deployment."
          echo ""
          echo "[INFO] 🔗 Branch URL: https://github.com/${{ github.repository }}/tree/$PREVIEW_BRANCH"

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const previewId = '${{ steps.branch-name.outputs.branch_name }}';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Preview ID generated: ${previewId}`
            });