name: Publish Documentation
run-name: Publish by @${{ github.actor }}

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11 + uv
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: '3.11'
    - name: Install dependencies
      shell: bash
      run: uv sync --group test
    - name: Build documentation
      run: make build
    - name: Verify build output exists
      run: |
        if [ ! -d build ]; then
          echo "Error: build/ directory was not created."
          exit 1
        fi